### ISSUE TITLE
Aula / oled support? AMS 1.5.4

### ISSUE THREAD

**Issue by Nazgile94** [hanai3Bi/Switch-OC-Suite#10]
Hey, greate job btw!

want to play "somethingrar" with overclocked ram , i have a aula switch and ams 1.5.4 

currently no support for oled switch and 1.5.4?

my hw infos:

cpu speedo 0 1697
cpu speedo 1 1383
cpu speedo 2 gpu val 1711
soc speedo 0 1728
soc speedo 2 1408

are these good values for oc?

**Comment by hanai3Bi** [comment]
AMS 1.5.4 is still in prelease. 
i will build release for 1.5.4 when it actually comes out as regular release.
and your speedo is good

**Comment by Nazgile94** [comment]
is aula supported?
bcs i just see erista and mariko

**Comment by WobbleTheHutt** [comment]
current loader.kip works fine with AMS 1.5.4 pre

**Comment by Nazgile94** [comment]
with oled switch too?

**Comment by hanai3Bi** [comment]
mariko means all v2 switches

**Comment by Cooler3D** [comment]
> with oled switch too?

Compatible with every single Nintendo Switch.

**Comment by cucholix** [comment]
I'm on ams 1.5.4 pre-release, my Switch is Erista, RAM OC works but in in the overlay doesn't appears the option to OC CPU to 2091.

**Comment by hanai3Bi** [comment]
> I'm on ams 1.5.4 pre-release, my Switch is Erista, RAM OC works but in the overlay doesn't appears the option to OC CPU to 2091. Edit: just tried under 1.5.3 and the issue persist... You need to change something in the online configurator in order to enable CPU at 2091?

please read readme carefully. unsafe frequencies are not enabled by default

**Comment by et4s** [comment]
> AMS 1.5.4 is still in prelease. i will build release for 1.5.4 when it actually comes out as regular release. and your speedo is good

@hanai3Bi it looks like it went out on regular release

**Comment by hanai3Bi** [comment]
thanks for letting know. it seems there's no change from pre-release so you can use 1.5.3 version on 1.5.4

I will release new version for 1.5.4 when new features are ready

**Comment by hanai3Bi** [comment]
closed as AMS 1.5.4 came out
