### ISSUE TITLE
Memory change no affect 

### ISSUE THREAD

**Issue by kd220** [hanai3Bi/Switch-OC-Suite#11]
I was able to get the switch oc suite on my oled but when I try to change the memory in handheld mode i only have two options 1600 or 1996 I change to 1996, but it doesn't have any effect when I check status monitor it still says ram usage is 1600mhz. I have enable turned on. The GPU and CPU are to be the only ones that actually have any effect when I change it but not memory the one I actually need any help?

**Comment by hanai3Bi** [comment]
make sure you correctly edited hekate_ipl.ini
and you are on the same AMS version as release file

**Comment by kd220** [comment]
I'm on fw 16.0.3 hekate 6.0.4 and ams 1.5.3 also I checked my bootloader folder on my sd and I see hekate_ipl not hekate_ipl.ini

**Comment by PiranhaMayhem** [comment]
I am having the same issue. When I edit my hekate_ipl.ini my switch won't boot after selecting the boot option (black screen). I don't mean to hijack the thread but maybe a solution will be found for both the OP and others. 

This is my hekate_ipl. Do you see anything wrong? 

[config]
autoboot=0
autoboot_list=0
bootwait=0
autohosoff=0
autonogc=1
updater2p=1
backlight=100

[CFW - sysMMC]
fss0=atmosphere/package3
kip1patch=nosigchk
atmosphere=1
emummc_force_disable=1
icon=bootloader/res/icon_payload.bmp

[CFW - emuMMC]
fss0=atmosphere/package3
kip1patch=nosigchk
emummcforce=1
atmosphere=1
icon=bootloader/res/icon_payload.bmp

[Stock - sysMMC]
fss0=atmosphere/package3
emummc_force_disable=1
stock=1
icon=bootloader/res/icon_switch.bmp

**Comment by lifson** [comment]
> I'm on fw 16.0.3 hekate 6.0.4 and ams 1.5.3 also I checked my bootloader folder on my sd and I see hekate_ipl not hekate_ipl.ini

That doesn't sound like something is wrong with your ini file, its just seems like you don't have "view extensions" turned on. If you're in windows:

Open File Explorer (open any folder).
Click the View tab.
Select "File name extension"
Optionally, you can enable Hidden items.
Filename extensions will now be visible.

![image](https://github.com/hanai3Bi/Switch-OC-Suite/assets/74938344/1f082448-17c0-4da4-80f9-b6e56b95e25b)

**Comment by kd220** [comment]
Was able to get it working thank you both
