### ISSUE TITLE
After Installation problems

### ISSUE THREAD

**Issue by garobcsi** [hanai3Bi/Switch-OC-Suite#14]
sys-clk nro dosen't work anymore.
All of my sys-clk settings are gone.

**Comment by garobcsi** [comment]
But it works perfectly

**Comment by hanai3Bi** [comment]
sys-clk nro is not supported. only overlay(included with zip) is supported

**Comment by hanai3Bi** [comment]
and for sys-clk config, copy /config/sys-clk/config.ini to /config/sys-clk-oc/  
i changed the config directory on purpose
