### ISSUE TITLE
Erista RAM timings adaptation (mode 0)

### ISSUE THREAD

**Issue by i3sey** [hanai3Bi/Switch-OC-Suite#15]
Please add support for adapting timings for Erista as currently implemented for MARIKO.

**Comment by i3sey** [comment]
I want use full potential of my Erista RAM but cooler3d does not optimize Erista in his project, so I backed to oc suite.

**Comment by hanai3Bi** [comment]
Isn't 2131 possible on erista with overvolting? what are you trying to achieve?
I don't have erista for testing, but maybe will implement in future

**Comment by ChanseyIsTheBest** [comment]
I have not heard of 2131 being stable for anyone for Eristra with OV. The highest I have heard being stable for very few units is 2099 with OV which is a 5% at very most more like 2% performance increase over 1996 which really isn't worth it due to its lack of stability.

**Comment by krakotay** [comment]
> Isn't 2131 already possible on erista with overvolting? what are you trying to achieve?

In mariko with 4ifir we can have stable 2666 MHz RAM. I unf. have "just" 2534 MHz, but it also much bigger that on Erista

**Comment by i3sey** [comment]
> Isn't 2131 already possible on erista with overvolting? what are you trying to achieve? I don't have erista for testing, but maybe will implement in future

I mean timings optimization
![Screenshot_20230522-105048](https://github.com/hanai3Bi/Switch-OC-Suite/assets/86531179/aa2826f5-16a1-46d1-ae08-b0f61eac099e)

**Comment by hanai3Bi** [comment]
I know what you mean.
I don't have a spare erista for testing, and it's not my high priority. cooler will implement it for you, since he said he will do it 'over a year ago'

**Comment by Cooler3D** [comment]
> for more than one year

Are you sure that's what I said?

Any way, since you're busy with the "correct" implementation of unsafe 2400 MHz for Mariko, and nobody cares about the poor fellows with ERISTA-s, I have no other choice but to deal with this issue.
