### ISSUE TITLE
[TODO] Configurator Homebrew

### ISSUE THREAD

**Issue by hanai3Bi** [hanai3Bi/Switch-OC-Suite#16]
todo : make homebrew app, so users can adjust configuration without need of web browser

**Comment by hanai3Bi** [comment]
add export option

**Comment by cucholix** [comment]
There's plans to make a sys-clk manager fork to make it compatible with sys-clk-oc?

**Comment by monstrosities** [comment]
I would also like to have the sys-clk manager back if it's possible, it makes it really easy to manage and see values for all your games at once.

**Comment by hanai3Bi** [comment]
I think the reason why KazushiMe stopped working with manager app is because of UI library bugs?
the UI library is not being updated and think has some problems.

I could check out manager, but it's my lowest priority, and I don't have good reason to work on it when you can already do it on overlay.
