### ISSUE TITLE
Patching pcv and ptm sysmodules at boot without loader.kip

### ISSUE THREAD

**Issue by wanderingmeow** [hanai3Bi/Switch-OC-Suite#18]
As demonstrated in [sys-patch](https://github.com/ITotalJustice/sys-patch/blob/master/sysmod/src/main.cpp), any sysmodules in [title list](https://switchbrew.org/wiki/Title_list) can be patched at boot with the usage of `svcReadDebugProcessMemory` and `svcWriteDebugProcessMemory`, including those loaded before SD card initialization (cannot be patched by `.ips` files).

If this could be implemented in sys-clk-OC, then:
- No need to compile loader.kip for every Atmosphere-NX release.
- Out-of-the-box experience, no configuration required.
- Easy integration with configurator in overlay or homebrew app.
- One may change DRAM timing or other parameters without reboot.

Some issues might arise:
- Some parameters might be initialized and stored in bss segments or even heap segments.
- DRAM training data at 1600 MHz shall be invalidated for new frequency table, or requires more meticulous handling.

**Comment by hanai3Bi** [comment]
yes. I did see sys-patch. i forked the repo to test if it suits this project.
I will do some tests and see what i can do, since users don't have to manually edit hekate_ipl.ini

**Comment by ITotalJustice** [comment]
if you need any help getting this to work / understanding my code, feel free to ask :)

**Comment by hanai3Bi** [comment]
closed as #33 handles issue
