### ISSUE TITLE
Erista “unsafe” CPU frequencies not available 

### ISSUE THREAD

**Issue by ajbritain4** [hanai3Bi/Switch-OC-Suite#2]
First of all thank you so much for continuing this - it works on my Switch perfectly.

On Erista I’m not able to set CPU frequencies higher than 1785 either on official charger or docked as the options in sys-clk don’t go any higher. 

I have the “unsafe” line added in config.ini and the higher frequencies were working fine using the older 1.5.0 build.

**Comment by hanai3Bi** [comment]
I changed config directory to /config/sys-clk-oc, so that it does not conflct with normal sys-clk.
I think you edited wrong ini file. I checked and works fine

**Comment by ajbritain4** [comment]
You’re absolutely right thanks - i wasn’t editing the right .ini file. The readme still says it’s in the sys-clk directory so I got them mixed up!
