### ISSUE TITLE
Question: Keep sys-clk installed?

### ISSUE THREAD

**Issue by misantronic** [hanai3Bi/Switch-OC-Suite#20]
The installation is a little unclear for me to weather I have to keep my sys-clk installtion or do I need to get rid of it?
When keeping sys-clk, afterwards my sys-click-manager will not work anymore.

**Comment by misantronic** [comment]
ok, so the way I understand it is that it‘s installed as addition to sys-clk. at least this is how it works for me

**Comment by hanai3Bi** [comment]
modified sys-clk included in SdOut.zip overwrites vanilla sys-clk, so no need to manually uninstsall.

sys-clk homebrew is not supported
