### ISSUE TITLE
TOTK Crash with Erista 1862 RAM Overclock 

### ISSUE THREAD

**Issue by MastrLnk** [hanai3Bi/Switch-OC-Suite#23]
I used ram overclocks on Hyrule Warriors Age of Calamity just fine but TOTK will freeze without error code after a few minutes. I have no idea what to do and can't find anything to fix it. Is this just a hardware lottery with voltage?

**Comment by hanai3Bi** [comment]
yes. you can try raising the voltage to see if it works.
If it is not a critical issue related with oc-suite, i recommend using "Discussions"

**Comment by MastrLnk** [comment]
Sorry for not getting back  quicker but I raised voltage and now don't have hard crashes but instead atmosphere crashes so I think my ram is real badly binned.
