### ISSUE TITLE
Missing files?

### ISSUE THREAD

**Issue by Muzika** [hanai3Bi/Switch-OC-Suite#25]
I remember using KazushiMe's version last year and it has a modified sys-clk-oc & ReverseNX-RT bundled in it. I can't find these files in this version of Switch OC Suite. Where do I get these 2 files? As far as I know the regular sys-clk-oc & ReverseNX-RT doesn't work out of the box.

*Edit: What I'm talking about are the .ovl files inside the /switch/.overlays/ folder for sys-clk-oc & ReverseNX-RT.

**Comment by hanai3Bi** [comment]
Sdout.zip
