### ISSUE TITLE
[Question] Unsafe DRAM frequencies?

### ISSUE THREAD

**Issue by anthqiu** [hanai3Bi/Switch-OC-Suite#34]
From [sys-clk-OC/README.md](https://github.com/hanai3Bi/Switch-OC-Suite/blob/master/Source/sys-clk-OC/README.md#mem-clocks) it seems that for Mariko Switches MEM frequency can go up to `2400MHz`.

However, frequencies beyond `1996MHz` are hidden even if `allow_unsafe_freq=1` is set in the config. Also, there's no mention of unsafe DRAM frequency in this project's main README as well.

Is it disabled for a reason, or is it just not implemented yet?

**Comment by hanai3Bi** [comment]
use online configurator for dram customization

**Comment by anthqiu** [comment]
got it, thanks!
