### ISSUE TITLE
RAM can no longer be overclocked

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [hanai3Bi/Switch-OC-Suite#35]
I have an Oled Switch on Firmware version 16.1.0 with OC Suite 1.8.1 and hekate 6.0.6
My global profile has the ram set to 1996mhz, but its no longer getting applied.
Even disabling the global profile and trying to raise the ram clock via the app profile or temporary profile does nothing.
Changing CPU and GPU clocks still works fine.

**Comment by hanai3Bi** [comment]
your hekate_ipl.ini probably got overwritten while updating AMS/hekate

**Comment by VorgonBattlecruiser** [comment]
> your hekate_ipl.ini probably got overwritten while updating AMS/hekate

That is exactly what must have happened!
Thank you so much.
