### ISSUE TITLE
Request - safe values for CPU and GPU also

### ISSUE THREAD

**Issue by sauliiin** [hanai3Bi/Switch-OC-Suite#58]
If possible, I would like more overclocking options to be included, especially for the CPU and GPU.I suggest the values available here as the limit: https://github.com/rashevskyv/sys-clk-OC.

Another suggestion and sorry for the intrusion. Although the advantage is small, this sys-clk mod (https://github.com/jope82/sys-clk-uncapped-gpu-and-other-extras/releases/tag/2.0.0_a) runs better than the original , especially on loadings. Already theuyed it with your load.kip and works flawlessly.

I don't have knowledge of C++, but I can get by in C. If you need any help and if i have the knowlage to do so, I'm at your disposal.

**Comment by hanai3Bi** [comment]
1. what do you mean by more overclocking options? If you mean higher CPU/GPU frequencies, they will not be included, so you will have to edit source code yourself.

2. I already provide sys-clk-oc. you are free to use vanilla sys-clk or any other fork, but i recommend using sys-clk-oc. up to date version of sys-clk-oc is released in our discord.


3. also what you mean by better loading? what does sys-clk load? If you want a feature that is available on sys-clk forks, but not on sys-clk-oc, you are always welcome to suggest new features. (Except for governor. I'm working on proper governor, but no ETA. old governor is very bad and can cause worse performance and power savings, so it is removed)

**Comment by hanai3Bi** [comment]
https://github.com/hanai3Bi/Switch-OC-Suite/blob/master/Source/sys-clk-OC/README.md

check official sys-clk-oc readme file, not random things

**Comment by sauliiin** [comment]
Hi, mate! 

Sorry for the request. Actually, I'm quite satisfied with my settings and kind of know a way around. But I see that many people are lost, don't know what to do, or are afraid to do so. 

Let me clarify.

1 - Actually, would be nice if we have just safe overclocking options and a few underclock (pehaps two loader.kip files, one for those that really dont worry - with unsafe values, and another one universal). Example: Mariko CPU: 1963 (official and safe max for Mariko), 1887, 1785... Mariko GPU:  998 (safe max for Mariko due to power draw), 921,  844...
 
2 -  Didn't know you provide an up to date sys-clk-oc on discord. Will search the discord group. But one feature that I like is the capability to go beyond 614 even on handheld mode. Since I have a switch lite, that is acctually really usefull. I'm playing Hellblade: Senua's Sacrifice and 768 is the setting that give me the most stable fps.

3 - I mean, loading screen and boost mode. That  sys-clk fork I mentioned have a feature that set CPU to 1785 MHz and GPU to 76 MHz during boost mode. That happens normally on loadings screens.

**Comment by hanai3Bi** [comment]
1. sys-clk-oc by default doesn't let you select frequencies above 1963/998. well if you use other sys-clk forks, nothing i can do.
i can make it so that dvfs table doesn't include such frequencies without undervolting, but i didn't touch it because i dunno it has been like that for long time.

2. latest sys-clk-oc already includes option to uncap clocks. read sys-clk-oc readme, at the end.

3. 1785/76 is clock values of official boost mode. sys-clk-oc includes option to override boost mode clocks with user values. also read readme file for this

**Comment by sauliiin** [comment]
Yep! Just found it on read me. Thanks for point me in the right direction and sorry for being lazy and not reading it before. 

1, 2 - For me is not uncapped, but im using sys-clk manager from the fork I mentioned. Can you point me to the discord group? Couldnt fiund it.

3 - Nice! Wouild be nicier if we couild teak it on sys-clk-manager.

Sorry for that ammojnt of request and silly doubts, but I'm new on switch wporld and tryng to learn everything. I will be more carefful when reading.

**Comment by hanai3Bi** [comment]
it's nswitch 60fps discord

**Comment by sauliiin** [comment]
Thanks, mate
