### ISSUE TITLE
Switch wont boot (mariko)

### ISSUE THREAD

**Issue by garobcsi** [hanai3Bi/Switch-OC-Suite#6]
after it was installed it won't boot to HOS (hekete still accessible)

**Comment by garobcsi** [comment]
any ideas ?

**Comment by garobcsi** [comment]
low firmware is a problem?

**Comment by hanai3Bi** [comment]
sorry for the inconvenience. I think lastest release file had some problems, so I removed them.
please revert back to v1.2
