### ISSUE TITLE
[TODO] Mariko Ram timings

### ISSUE THREAD

**Issue by hanai3Bi** [hanai3Bi/Switch-OC-Suite#7]
1. remove auto adjustment and leave only specific clocks with proper ram timings (or just add as presets in advanced config)

2. implement proper 2400 ram oc ??

**Comment by WobbleTheHutt** [comment]
Right now i'm playing with my ram and auto adjustment with memtesternx and have my ram with auto adjustment up to 2233.6. (booting to EMUMMC so as to not trash the OS while testing) and I noticed a bug that the displayed ram clock in the overlay only shows up to 2132 (it does apply correctly!) and was wondering if we could get this fixed with the next release.

**Comment by hanai3Bi** [comment]
oc-suite's auto adjustment algorithm is bad and it's better to use noadjust.
I'm still figuring out correct table parameters so hopefully in next release auto adjust will be fixed and push up to 2400 mem

**Comment by WobbleTheHutt** [comment]
> oc-suite's auto adjustment algorithm is bad and it's better to use noadjust (noadjust 2131 much better than auto 2250) I'm still figuring out correct table parameters so hopefully in next release auto adjust will be fixed and able to push up to 2400 mem.

Yeah but my ram IC's aren't stable with out adjusting timings. If you like I'm happy to help you test things to increase sample size I'm quite familiar with Ddr4 ram timings and have emummc setup specific to test with as then I don't have to worry about eating sysnand. 

Probably the thing to do would be hwv people identify their ram ICs and have profiles based on that along with a set of loose, tight, extreme timings. The best settings are going to vary switch to switch. 

I'll try to setup 3 loader.kips with the 3 straps at the same clocks and poke em with a hex editor later this weekend.

**Comment by hanai3Bi** [comment]
yes, I have thought about that. I had considered reading ram id from fuse dumped from hekate, and adjust timings according to that. but figuring out the correct values for mtc table is headache. 
Right now my priority is fixing auto adjust algorithm, and implementing 2400 ram oc.

**Comment by Cooler3D** [comment]
> yes, I have thought about that. I had considered reading ram id from fuse dumped from hekate, and adjust timings according to that. but figuring out the correct values for mtc table is headache. Right now my priority is fixing auto adjust algorithm, and implementing 2400 ram oc.

Before you start, if possible, check your telegram. I sent you an idea that came up in it.

**Comment by hanai3Bi** [comment]
advanced memory configuration will be included maybe in next release

**Comment by hanai3Bi** [comment]
implemented. will be released when i feel like
