### ISSUE TITLE
Atmosphere doesn't boot on 1.5.3

### ISSUE THREAD

**Issue by Janthor** [hanai3Bi/Switch-OC-Suite#8]
After updating to version 1.5.3, atmosphere stopped booting, it hangs on a black screen, reverting back to 1.5.2 fixed the issue.
I'm on a Mariko Switch Lite.

**Comment by hanai3Bi** [comment]
did you update to oc-suite built for 1.5.3? 1.5.2 and 1.5.3 are not compatible.
I tested with 3 of my consoles and all works with latest version.
If you are on latest oc-suite version and ams 1.5.3, but problem still exists, let me know. I will investigate ASAP.

**Comment by hanai3Bi** [comment]
updated release with legacy build, which is 1.5.2 version(which seems to have no issues) compiled for 1.5.3. This should fix the issue if the problem was caused by my code changes. test and let me know.

**Comment by Janthor** [comment]
sorry about this, didn't know there were dependencies between AMS versions, updated AMS and used the AIO package and it worked perfectly.
