### ISSUE TITLE
Applying this breaks LayeredFS functionality

### ISSUE THREAD

**Issue by 20excal07** [hanai3Bi/Switch-OC-Suite#9]
I'm not sure why, but when I booted into Atmosphere with the kips patch installed, suddenly my game mods aren't being applied. Is this a known issue or am I missing something?

**Comment by hanai3Bi** [comment]
I tested with my console and layeredfs works for me.
Can you tell me what AMS version? layeredfs not working for all games or specific games?

**Comment by hanai3Bi** [comment]
updated release with legacy build, which is 1.5.2 version(which seems to have no issues) compiled for 1.5.3. This should fix the issue if the problem was caused by my code changes. test and let me know.

**Comment by 20excal07** [comment]
I was actually on AMS 1.5.2 when I tried it, and it seems to break with all games. I was using the one on your v1.2 release, if that helps. I have yet to update to AMS 1.5.3 - should I do that?

**Comment by hanai3Bi** [comment]
yes 1.5.2 and 1.5.3 are not compatible, hence each release is labeled with ams version.
and on that matter, it's your choice if you want to update or not. I always update to latest version

**Comment by 20excal07** [comment]
oh no, I meant I was using the patch that you compiled for 1.5.2 when I tested. I just figured that since you compiled again for 1.5.3 but using the code from 1.5.2, it might shed some new information? Sorry for the misunderstanding lol. AMS wouldn't boot if I used the wrong version :p

**Comment by 20excal07** [comment]
So I just tested 1.5.2 again and now it works with no issues? Very strange... I'll keep using it until further notice.

**Comment by hanai3Bi** [comment]
ah so you were using 1.5.2-v1.2 on AMS 1.5.2? I misunderstood. 
Then I think you might have misspelled something in hekate_ipl.ini>
anyways glad to see the problem was fixed
